#pragma once
#include <Fission/core/graphics.hpp>

FISSION_NAMESPACE_BEGIN

struct Draw_Data {
	u32 total_vtx_count {0};
	u32 total_idx_count {0};

	u32 vtx_offset {0};
	u32 idx_offset {0};
	u32 vtx_count  {0};
	u32 idx_count  {0};

public:
    // Call reset() before each submit
	inline void reset() { *this = Draw_Data {}; }

    // Call start_new_draw() after each draw call
	inline void start_new_draw() {
		vtx_offset = total_vtx_count;
		idx_offset = total_idx_count;
		vtx_count = 0;
		idx_count = 0;
	}
};

FISSION_NAMESPACE_END

namespace vk
{

#define X_VULKAN_FORMATS \
    X(VK_FORMAT_UNDEFINED) \
    X(VK_FORMAT_R4G4_UNORM_PACK8) \
    X(VK_FORMAT_R4G4B4A4_UNORM_PACK16) \
    X(VK_FORMAT_B4G4R4A4_UNORM_PACK16) \
    X(VK_FORMAT_R5G6B5_UNORM_PACK16) \
    X(VK_FORMAT_B5G6R5_UNORM_PACK16) \
    X(VK_FORMAT_R5G5B5A1_UNORM_PACK16) \
    X(VK_FORMAT_B5G5R5A1_UNORM_PACK16) \
    X(VK_FORMAT_A1R5G5B5_UNORM_PACK16) \
    X(VK_FORMAT_R8_UNORM) \
    X(VK_FORMAT_R8_SNORM) \
    X(VK_FORMAT_R8_USCALED) \
    X(VK_FORMAT_R8_SSCALED) \
    X(VK_FORMAT_R8_UINT) \
    X(VK_FORMAT_R8_SINT) \
    X(VK_FORMAT_R8_SRGB) \
    X(VK_FORMAT_R8G8_UNORM) \
    X(VK_FORMAT_R8G8_SNORM) \
    X(VK_FORMAT_R8G8_USCALED) \
    X(VK_FORMAT_R8G8_SSCALED) \
    X(VK_FORMAT_R8G8_UINT) \
    X(VK_FORMAT_R8G8_SINT) \
    X(VK_FORMAT_R8G8_SRGB) \
    X(VK_FORMAT_R8G8B8_UNORM) \
    X(VK_FORMAT_R8G8B8_SNORM) \
    X(VK_FORMAT_R8G8B8_USCALED) \
    X(VK_FORMAT_R8G8B8_SSCALED) \
    X(VK_FORMAT_R8G8B8_UINT) \
    X(VK_FORMAT_R8G8B8_SINT) \
    X(VK_FORMAT_R8G8B8_SRGB) \
    X(VK_FORMAT_B8G8R8_UNORM) \
    X(VK_FORMAT_B8G8R8_SNORM) \
    X(VK_FORMAT_B8G8R8_USCALED) \
    X(VK_FORMAT_B8G8R8_SSCALED) \
    X(VK_FORMAT_B8G8R8_UINT) \
    X(VK_FORMAT_B8G8R8_SINT) \
    X(VK_FORMAT_B8G8R8_SRGB) \
    X(VK_FORMAT_R8G8B8A8_UNORM) \
    X(VK_FORMAT_R8G8B8A8_SNORM) \
    X(VK_FORMAT_R8G8B8A8_USCALED) \
    X(VK_FORMAT_R8G8B8A8_SSCALED) \
    X(VK_FORMAT_R8G8B8A8_UINT) \
    X(VK_FORMAT_R8G8B8A8_SINT) \
    X(VK_FORMAT_R8G8B8A8_SRGB) \
    X(VK_FORMAT_B8G8R8A8_UNORM) \
    X(VK_FORMAT_B8G8R8A8_SNORM) \
    X(VK_FORMAT_B8G8R8A8_USCALED) \
    X(VK_FORMAT_B8G8R8A8_SSCALED) \
    X(VK_FORMAT_B8G8R8A8_UINT) \
    X(VK_FORMAT_B8G8R8A8_SINT) \
    X(VK_FORMAT_B8G8R8A8_SRGB) \
    X(VK_FORMAT_A8B8G8R8_UNORM_PACK32) \
    X(VK_FORMAT_A8B8G8R8_SNORM_PACK32) \
    X(VK_FORMAT_A8B8G8R8_USCALED_PACK32) \
    X(VK_FORMAT_A8B8G8R8_SSCALED_PACK32) \
    X(VK_FORMAT_A8B8G8R8_UINT_PACK32) \
    X(VK_FORMAT_A8B8G8R8_SINT_PACK32) \
    X(VK_FORMAT_A8B8G8R8_SRGB_PACK32) \
    X(VK_FORMAT_A2R10G10B10_UNORM_PACK32) \
    X(VK_FORMAT_A2R10G10B10_SNORM_PACK32) \
    X(VK_FORMAT_A2R10G10B10_USCALED_PACK32) \
    X(VK_FORMAT_A2R10G10B10_SSCALED_PACK32) \
    X(VK_FORMAT_A2R10G10B10_UINT_PACK32) \
    X(VK_FORMAT_A2R10G10B10_SINT_PACK32) \
    X(VK_FORMAT_A2B10G10R10_UNORM_PACK32) \
    X(VK_FORMAT_A2B10G10R10_SNORM_PACK32) \
    X(VK_FORMAT_A2B10G10R10_USCALED_PACK32) \
    X(VK_FORMAT_A2B10G10R10_SSCALED_PACK32) \
    X(VK_FORMAT_A2B10G10R10_UINT_PACK32) \
    X(VK_FORMAT_A2B10G10R10_SINT_PACK32) \
    X(VK_FORMAT_R16_UNORM) \
    X(VK_FORMAT_R16_SNORM) \
    X(VK_FORMAT_R16_USCALED) \
    X(VK_FORMAT_R16_SSCALED) \
    X(VK_FORMAT_R16_UINT) \
    X(VK_FORMAT_R16_SINT) \
    X(VK_FORMAT_R16_SFLOAT) \
    X(VK_FORMAT_R16G16_UNORM) \
    X(VK_FORMAT_R16G16_SNORM) \
    X(VK_FORMAT_R16G16_USCALED) \
    X(VK_FORMAT_R16G16_SSCALED) \
    X(VK_FORMAT_R16G16_UINT) \
    X(VK_FORMAT_R16G16_SINT) \
    X(VK_FORMAT_R16G16_SFLOAT) \
    X(VK_FORMAT_R16G16B16_UNORM) \
    X(VK_FORMAT_R16G16B16_SNORM) \
    X(VK_FORMAT_R16G16B16_USCALED) \
    X(VK_FORMAT_R16G16B16_SSCALED) \
    X(VK_FORMAT_R16G16B16_UINT) \
    X(VK_FORMAT_R16G16B16_SINT) \
    X(VK_FORMAT_R16G16B16_SFLOAT) \
    X(VK_FORMAT_R16G16B16A16_UNORM) \
    X(VK_FORMAT_R16G16B16A16_SNORM) \
    X(VK_FORMAT_R16G16B16A16_USCALED) \
    X(VK_FORMAT_R16G16B16A16_SSCALED) \
    X(VK_FORMAT_R16G16B16A16_UINT) \
    X(VK_FORMAT_R16G16B16A16_SINT) \
    X(VK_FORMAT_R16G16B16A16_SFLOAT) \
    X(VK_FORMAT_R32_UINT) \
    X(VK_FORMAT_R32_SINT) \
    X(VK_FORMAT_R32_SFLOAT) \
    X(VK_FORMAT_R32G32_UINT) \
    X(VK_FORMAT_R32G32_SINT) \
    X(VK_FORMAT_R32G32_SFLOAT) \
    X(VK_FORMAT_R32G32B32_UINT) \
    X(VK_FORMAT_R32G32B32_SINT) \
    X(VK_FORMAT_R32G32B32_SFLOAT) \
    X(VK_FORMAT_R32G32B32A32_UINT) \
    X(VK_FORMAT_R32G32B32A32_SINT) \
    X(VK_FORMAT_R32G32B32A32_SFLOAT) \
    X(VK_FORMAT_R64_UINT) \
    X(VK_FORMAT_R64_SINT) \
    X(VK_FORMAT_R64_SFLOAT) \
    X(VK_FORMAT_R64G64_UINT) \
    X(VK_FORMAT_R64G64_SINT) \
    X(VK_FORMAT_R64G64_SFLOAT) \
    X(VK_FORMAT_R64G64B64_UINT) \
    X(VK_FORMAT_R64G64B64_SINT) \
    X(VK_FORMAT_R64G64B64_SFLOAT) \
    X(VK_FORMAT_R64G64B64A64_UINT) \
    X(VK_FORMAT_R64G64B64A64_SINT) \
    X(VK_FORMAT_R64G64B64A64_SFLOAT) \
    X(VK_FORMAT_B10G11R11_UFLOAT_PACK32) \
    X(VK_FORMAT_E5B9G9R9_UFLOAT_PACK32) \
    X(VK_FORMAT_D16_UNORM) \
    X(VK_FORMAT_X8_D24_UNORM_PACK32) \
    X(VK_FORMAT_D32_SFLOAT) \
    X(VK_FORMAT_S8_UINT) \
    X(VK_FORMAT_D16_UNORM_S8_UINT) \
    X(VK_FORMAT_D24_UNORM_S8_UINT) \
    X(VK_FORMAT_D32_SFLOAT_S8_UINT) \
    X(VK_FORMAT_BC1_RGB_UNORM_BLOCK) \
    X(VK_FORMAT_BC1_RGB_SRGB_BLOCK) \
    X(VK_FORMAT_BC1_RGBA_UNORM_BLOCK) \
    X(VK_FORMAT_BC1_RGBA_SRGB_BLOCK) \
    X(VK_FORMAT_BC2_UNORM_BLOCK) \
    X(VK_FORMAT_BC2_SRGB_BLOCK) \
    X(VK_FORMAT_BC3_UNORM_BLOCK) \
    X(VK_FORMAT_BC3_SRGB_BLOCK) \
    X(VK_FORMAT_BC4_UNORM_BLOCK) \
    X(VK_FORMAT_BC4_SNORM_BLOCK) \
    X(VK_FORMAT_BC5_UNORM_BLOCK) \
    X(VK_FORMAT_BC5_SNORM_BLOCK) \
    X(VK_FORMAT_BC6H_UFLOAT_BLOCK) \
    X(VK_FORMAT_BC6H_SFLOAT_BLOCK) \
    X(VK_FORMAT_BC7_UNORM_BLOCK) \
    X(VK_FORMAT_BC7_SRGB_BLOCK) \
    X(VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK) \
    X(VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK) \
    X(VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK) \
    X(VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK) \
    X(VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK) \
    X(VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK) \
    X(VK_FORMAT_EAC_R11_UNORM_BLOCK) \
    X(VK_FORMAT_EAC_R11_SNORM_BLOCK) \
    X(VK_FORMAT_EAC_R11G11_UNORM_BLOCK) \
    X(VK_FORMAT_EAC_R11G11_SNORM_BLOCK) \
    X(VK_FORMAT_ASTC_4x4_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_4x4_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_5x4_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_5x4_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_5x5_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_5x5_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_6x5_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_6x5_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_6x6_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_6x6_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_8x5_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_8x5_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_8x6_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_8x6_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_8x8_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_8x8_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_10x5_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_10x5_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_10x6_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_10x6_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_10x8_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_10x8_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_10x10_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_10x10_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_12x10_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_12x10_SRGB_BLOCK) \
    X(VK_FORMAT_ASTC_12x12_UNORM_BLOCK) \
    X(VK_FORMAT_ASTC_12x12_SRGB_BLOCK) \
    X(VK_FORMAT_G8B8G8R8_422_UNORM) \
    X(VK_FORMAT_B8G8R8G8_422_UNORM) \
    X(VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM) \
    X(VK_FORMAT_G8_B8R8_2PLANE_420_UNORM) \
    X(VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM) \
    X(VK_FORMAT_G8_B8R8_2PLANE_422_UNORM) \
    X(VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM) \
    X(VK_FORMAT_R10X6_UNORM_PACK16) \
    X(VK_FORMAT_R10X6G10X6_UNORM_2PACK16) \
    X(VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16) \
    X(VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16) \
    X(VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16) \
    X(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16) \
    X(VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16) \
    X(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16) \
    X(VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16) \
    X(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16) \
    X(VK_FORMAT_R12X4_UNORM_PACK16) \
    X(VK_FORMAT_R12X4G12X4_UNORM_2PACK16) \
    X(VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16) \
    X(VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16) \
    X(VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16) \
    X(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16) \
    X(VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16) \
    X(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16) \
    X(VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16) \
    X(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16) \
    X(VK_FORMAT_G16B16G16R16_422_UNORM) \
    X(VK_FORMAT_B16G16R16G16_422_UNORM) \
    X(VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM) \
    X(VK_FORMAT_G16_B16R16_2PLANE_420_UNORM) \
    X(VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM) \
    X(VK_FORMAT_G16_B16R16_2PLANE_422_UNORM) \
    X(VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM) \
    X(VK_FORMAT_G8_B8R8_2PLANE_444_UNORM) \
    X(VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16) \
    X(VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16) \
    X(VK_FORMAT_G16_B16R16_2PLANE_444_UNORM) \
    X(VK_FORMAT_A4R4G4B4_UNORM_PACK16) \
    X(VK_FORMAT_A4B4G4R4_UNORM_PACK16) \
    X(VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK) \
    X(VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK) \
    X(VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG) \
    X(VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG) \
    X(VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG) \
    X(VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG) \
    X(VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG) \
    X(VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG) \
    X(VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG) \
    X(VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG) \
    X(VK_FORMAT_R16G16_S10_5_NV) \

#define X_VULKAN_COLORSPACES \
    X(VK_COLOR_SPACE_SRGB_NONLINEAR_KHR) \
    X(VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT) \
    X(VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT) \
    X(VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT) \
    X(VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT) \
    X(VK_COLOR_SPACE_BT709_LINEAR_EXT) \
    X(VK_COLOR_SPACE_BT709_NONLINEAR_EXT) \
    X(VK_COLOR_SPACE_BT2020_LINEAR_EXT) \
    X(VK_COLOR_SPACE_HDR10_ST2084_EXT) \
    X(VK_COLOR_SPACE_DOLBYVISION_EXT) \
    X(VK_COLOR_SPACE_HDR10_HLG_EXT) \
    X(VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT) \
    X(VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT) \
    X(VK_COLOR_SPACE_PASS_THROUGH_EXT) \
    X(VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT) \
    X(VK_COLOR_SPACE_DISPLAY_NATIVE_AMD)

#define X_VULKAN_TRANSFORMS \
    X(VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR) \
    X(VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR) \
    X(VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR) \
    X(VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR) \
    X(VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR) \
    X(VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR) \
    X(VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR) \
    X(VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR) \
    X(VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR)

#define X_VULKAN_PRESENT_MODES \
    X(VK_PRESENT_MODE_IMMEDIATE_KHR) \
    X(VK_PRESENT_MODE_MAILBOX_KHR) \
    X(VK_PRESENT_MODE_FIFO_KHR) \
    X(VK_PRESENT_MODE_FIFO_RELAXED_KHR) \
    X(VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR) \
    X(VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR)

#define X_VULKAN_RESULTS \
    X(VK_SUCCESS) \
    X(VK_NOT_READY) \
    X(VK_TIMEOUT) \
    X(VK_EVENT_SET) \
    X(VK_EVENT_RESET) \
    X(VK_INCOMPLETE) \
    X(VK_ERROR_OUT_OF_HOST_MEMORY) \
    X(VK_ERROR_OUT_OF_DEVICE_MEMORY) \
    X(VK_ERROR_INITIALIZATION_FAILED) \
    X(VK_ERROR_DEVICE_LOST) \
    X(VK_ERROR_MEMORY_MAP_FAILED) \
    X(VK_ERROR_LAYER_NOT_PRESENT) \
    X(VK_ERROR_EXTENSION_NOT_PRESENT) \
    X(VK_ERROR_FEATURE_NOT_PRESENT) \
    X(VK_ERROR_INCOMPATIBLE_DRIVER) \
    X(VK_ERROR_TOO_MANY_OBJECTS) \
    X(VK_ERROR_FORMAT_NOT_SUPPORTED) \
    X(VK_ERROR_FRAGMENTED_POOL) \
    X(VK_ERROR_UNKNOWN) \
    X(VK_ERROR_OUT_OF_POOL_MEMORY) \
    X(VK_ERROR_INVALID_EXTERNAL_HANDLE) \
    X(VK_ERROR_FRAGMENTATION) \
    X(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS) \
    X(VK_PIPELINE_COMPILE_REQUIRED) \
    X(VK_ERROR_SURFACE_LOST_KHR) \
    X(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR) \
    X(VK_SUBOPTIMAL_KHR) \
    X(VK_ERROR_OUT_OF_DATE_KHR) \
    X(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR) \
    X(VK_ERROR_VALIDATION_FAILED_EXT) \
    X(VK_ERROR_INVALID_SHADER_NV) \
    X(VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR) \
    X(VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT) \
    X(VK_ERROR_NOT_PERMITTED_KHR) \
    X(VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT) \
    X(VK_THREAD_IDLE_KHR) \
    X(VK_THREAD_DONE_KHR) \
    X(VK_OPERATION_DEFERRED_KHR) \
    X(VK_OPERATION_NOT_DEFERRED_KHR) \
    X(VK_ERROR_COMPRESSION_EXHAUSTED_EXT) \
    X(VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT)

template <typename T>
char const* name(T t) {
    if constexpr (std::is_same_v<T,VkFormat>) {
        switch (t) {
            #define X(N) case N: return #N;
            X_VULKAN_FORMATS
            #undef X
            default: return "(Unknown VkFormat)";
        }
    }
    if constexpr (std::is_same_v<T,VkColorSpaceKHR>) {
        switch (t) {
            #define X(N) case N: return #N;
            X_VULKAN_COLORSPACES
            #undef X
            default: return "(Unknown VkColorSpaceKHR)";
        }
    }
    if constexpr (std::is_same_v<T,VkSurfaceTransformFlagBitsKHR>) {
        switch (t) {
            #define X(N) case N: return #N;
            X_VULKAN_TRANSFORMS
            #undef X
            default: return "(Unknown VkSurfaceTransformFlagBitsKHR)";
        }
    }
    if constexpr (std::is_same_v<T,VkPresentModeKHR>) {
        switch (t) {
            #define X(N) case N: return #N;
            X_VULKAN_PRESENT_MODES
            #undef X
            default: return "(Unknown VkSurfaceTransformFlagBitsKHR)";
        }
    }
    if constexpr (std::is_same_v<T,VkResult>) {
        switch (t) {
            #define X(N) case N: return #N;
            X_VULKAN_RESULTS
            #undef X
            default: return "(Unknown VkResult)";
        }
    }
}

}
