#pragma once

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
//#define NOGDICAPMASKS
//#define NOSYSMETRICS
#define NOMENUS
//#define NOICONS
//#define NOKEYSTATES
//#define NORASTEROPS
//#define NOSHOWWINDOW
//#define NOATOM
//#define NOCLIPBOARD
//#define NOCOLOR
//#define NOCTLMGR
#define NODRAWTEXT
//#define NOGDI
//#define NOKERNEL
//#define NONLS
//#define NOMEMMGR
//#define NOMETAFILE
//#define NOOPENFILE
#define NOSCROLL
//#define NOSOUND
//#define NOTEXTMETRIC
//#define NOWH
//#define NOCOMM
//#define NOKANJI
//#define NOHELP
//#define NOPROFILER
//#define NODEFERWINDOWPOS
//#define NOMCX

#include <windows.h>

// STOP DOING THIS WINDOWS, I DON'T WANT YOUR STUPID MACROS
#undef CreateWindow
#undef LoadLibrary
#undef LoadCursor
#undef MessageBox
#undef GetMessage
#undef SendMessage
#undef DispatchMessage
#undef DefWindowProc
#undef RegisterClass
#undef UnregisterClass
#undef SetWindowText
#undef GetWindowLongPtr
#undef SetWindowLongPtr
#undef GetMonitorInfo
