#pragma once

#define FISSION_MK_STR(X) #X

#define FISSION_VERSION_MAJ 0
#define FISSION_VERSION_MIN 1
#define FISSION_VERSION_PAT 0

#define _FISSION_VERSION_STRING(MAJ,MIN,PAT) FISSION_MK_STR(MAJ) "." FISSION_MK_STR(MIN) "." FISSION_MK_STR(PAT)

#define FISSION_VERSION_STRING _FISSION_VERSION_STRING(FISSION_VERSION_MAJ, FISSION_VERSION_MIN, FISSION_VERSION_PAT)

#define FISSION_COPYRIGHT_YEAR "2021"

#define FISSION_COMPANY_NAME "Lazergenix Software"

#define FISSION_COPYRIGHT "Copyright (c) " FISSION_COPYRIGHT_YEAR " " FISSION_COMPANY_NAME
